### ISSUE TITLE
VDB DDL Import support

### ISSUE THREAD

**Issue by kLeZ** [teiid/vdb-maven-plugin#5]
Hi guys.
Is there any plan to integrate the VDB DDL import syntax?

It could be really useful to have it, since the VDB DDL syntax now supports the DDL-FILE property inside a vdb.ddl and seems that this is the recommended way to construct a .vdb zip file for the current version of teiid.

Thanks a lot for your work.

**Comment by kLeZ** [comment]
I created the pull request #6 in order to support this behavior. I tried to change as least as possible.

**Comment by rareddy** [comment]
Accepted your PR. Thank you.
